default_config:

homeassistant:
  name: !secret home_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages

lovelace:
  mode: yaml
  resources:
    - url: /local/custom_ui/vertical-stack-in-card.js
      type: module

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url

zone:
wake_on_lan:

api:
alexa:
  smart_home:

tts:
  - platform: google_translate

shelly:
  discovery: false
  version: true #add version sensor
  sensors:
    - all
  devices:      #devices to be added
    - id: "26722D"
      name: Luz auxiliar
    - id: "40f5202d3117"
      name: Luz Despacho
    - id: "40f5202e07d9"
      name: Luz Dormitorio

meross:
  username: !secret meross_userame
  password: !secret meross_password
  scan_interval: 30

alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
