automation:
  - id: alarm_armed_away
    alias: "[Alarm] Away Mode Armed"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "armed_away"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10010 # Alarma Activada.
          ringtone_vol: 20
      - service: notify.telegram
        data:
          message: "* Alarma Activada*. Adios :)"

  - id: alarm_armed_home
    alias: "[Alarm] Home Mode Armed"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "armed_home"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10011 # Modo casa activado. Buenas noches
          ringtone_vol: 50
      - service: notify.telegram
        data:
          message: "*Modo noche activado*. Buenas noches."

  - id: alarm_arming_away
    alias: "[Alarm] Away Mode Arming"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "pending"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10012 # Activando alarma, revisa que puertas y ventanas esten cerradas
          ringtone_vol: 100
      - delay:
          seconds: 8
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10017 # Contador 22 Segundos
          ringtone_vol: 20

  - id: alarm_disarmed
    alias: "[Alarm] Disarmed"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "disarmed"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10014 # Alarma desactivada
          ringtone_vol: 20
      - service: notify.telegram
        data:
          message: "Alarma *desactivada*"
      - service: automation.turn_off
        entity_id: automation.sirena1
      - service: automation.turn_off
        entity_id: automation.sirena2
      - service: automation.turn_off
        entity_id: automation.sirena3

  - id: alarm_triggered
    alias: "[Alarm] Triggered"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "triggered"
    action:
      - service: automation.turn_on
        entity_id: automation.sirena1
      #    - service: switch.turn_on
      #      entity_id: switch.siren_switch
      - service: notify.telegram
        data:
          message: 'HA SALTADO LA ALARMA!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'

  ####################################################
  ################# S I R E N A ######################
  ####################################################
  - alias: "Sirena1"
    initial_state: False
    trigger:
      - platform: state
        entity_id: automation.sirena1
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.house
        state: "triggered"
    action:
      - service: automation.turn_off
        entity_id: automation.sirena3
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          # ringtone_id: 2
          ringtone_id: 10013
          ringtone_vol: 20
      - delay:
          seconds: 4
      - service: automation.turn_on
        entity_id: automation.sirena2

  - alias: "Sirena2"
    initial_state: False
    trigger:
      - platform: state
        entity_id: automation.sirena2
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.house
        state: "triggered"
    action:
      - service: automation.turn_off
        entity_id: automation.sirena1
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          # ringtone_id: 2
          ringtone_id: 10013
          ringtone_vol: 20
      - delay:
          seconds: 4
      - service: automation.turn_on
        entity_id: automation.sirena3

  - alias: "Sirena3"
    initial_state: False
    trigger:
      - platform: state
        entity_id: automation.sirena3
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.house
        state: "triggered"
    action:
      - service: automation.turn_off
        entity_id: automation.sirena2
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          # ringtone_id: 2
          ringtone_id: 10013
          ringtone_vol: 20
      - delay:
          seconds: 4
      - service: automation.turn_on
        entity_id: automation.sirena1
