automation:
  - id: alarm_armed_away
    alias: "[Alarm] Away Mode Armed"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "armed_away"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10001
          ringtone_vol: 5
      - service: notify.telegram
        data:
          message: "* Alarma Activada*. Adios :)"

  - id: alarm_armed_home
    alias: "[Alarm] Home Mode Armed"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "armed_home"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10002
          ringtone_vol: 5
      - service: notify.telegram
        data:
          message: "*Modo noche activado*. Buenas noches."

  - id: alarm_arming_away
    alias: "[Alarm] Away Mode Arming"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "pending"
    action:
      - delay:
          seconds: 3
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10004
          ringtone_vol: 5

  - id: alarm_disarmed
    alias: "[Alarm] Disarmed"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "disarmed"
    action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret aqara_gateway_mac
          ringtone_id: 10005
          ringtone_vol: 5
      - service: notify.telegram
        data:
          message: "Alarma *desactivada*"
      - service: script.security_stop_loop_sounds

  - id: alarm_triggered
    alias: "[Alarm] Triggered"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: "triggered"
    action:
      - service: script.security_alarm_loop_1
      - service: notify.telegram
        data:
          message: 'HA SALTADO LA ALARMA!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'

  - id: alarm_panic_mode
    alias: "[Alarm] Panic mode activated"
    trigger:
      platform: template
      value_template: "{{ states.alarm_control_panel.house.attributes.panic_mode == 'ACTIVE' }}"
    action:
      - service: notify.telegram
        data:
          message: "PANIC MODE ACTIVADO!!!"

  ####################################################
  ################# S I R E N A ######################
  ####################################################
  script:
  security_alarm_loop_1:
    sequence:
    - service: script.turn_off
      target:
        entity_id:
          - script.security_countdown_loop_1
          - script.security_countdown_loop_2
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 2 
        ringtone_vol: 10
    - service: script.turn_off
      entity_id: script.security_alarm_loop_2
    - delay: "00:00:6"
    - service: script.turn_on
      entity_id: script.security_alarm_loop_2
  security_alarm_loop_2:
    sequence:
    - service: script.turn_off
      target:
        entity_id:
          - script.security_countdown_loop_1
          - script.security_countdown_loop_2
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
        ringtone_id: 1 
        ringtone_vol: 10
    - service: script.turn_off
      entity_id: script.security_alarm_loop_1
    - delay: "00:00:10"
    - service: script.turn_on
      entity_id: script.security_alarm_loop_1
  security_stop_loop_sounds:
    alias: Stop Security Sound Scripts on Gateway
    sequence:
    - service: script.turn_off
      target:
        entity_id:
          - script.security_alarm_loop_1
          - script.security_alarm_loop_2
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret aqara_gateway_mac
