light:
  - platform: group
    name: Luz espejo Baño
    entities:
      - light.luz_bano_1
      - light.luz_bano_2

homeassistant:
  customize:
    switch.plug_158d000310c4a0:
      friendly_name: Luz mesilla Iván
    switch.shelly1_40f5202e07d9:
      friendly_name: Luz Dormitorio
    switch.shelly1_40f5202d3117:
      friendly_name: Luz Martín
    switch.shellyplug_s_26722d:
      friendly_name: Luz auxiliar
    switch.luz_mesilla_sara_mss210_main_channel:
      friendly_name: Luz mesilla Sara

automation:
  - id: "1578412911487"
    alias: Encender luz entrada cuando hay movimiento
    description: ""
    trigger:
      - entity_id: binary_sensor.motion_sensor_158d00044cce1a
        from: "off"
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
    action:
      - data:
          entity_id: light.gateway_light_04cf8cf312cd
        service: light.turn_on
  - id: "1578413039150"
    alias: Apagar luz entrada cuando no hay movimiento
    description: ""
    trigger:
      - entity_id: binary_sensor.motion_sensor_158d00044cce1a
        from: "on"
        platform: state
        to: "off"
    condition: []
    action:
      - data:
          entity_id: light.gateway_light_04cf8cf312cd
        service: light.turn_off
