# light:
#   - platform: xiaomi_miio
#     name: Luz espejo Baño 1
#     host: !secret luz_espejo_bano_1_ip
#     token: !secret luz_espejo_bano_1_token
#     model: philips.light.bulb
#   - platform: xiaomi_miio
#     name: Luz espejo Baño 2
#     host: !secret luz_espejo_bano_2_ip
#     token: !secret luz_espejo_bano_2_token
#     model: philips.light.bulb
#   - platform: group
#     name: Luz espejo Baño
#     entities:
#       - light.luz_espejo_bano_1
#       - light.luz_espejo_bano_2

discovery:
  ignore:
    - yeelight

yeelight:
  devices:
    !secret luz_vestidor_ip:
      name: Luz Vestidor

homeassistant:
  customize:
    # switch.shelly_shplg_s_26722d:
    #   friendly_name: Luz cómoda
    switch.plug_158d000310c4a0:
      friendly_name: Luz mesilla Iván

automation:
  - id: "1578412911487"
    alias: Encender luz entrada cuando hay movimiento
    description: ""
    trigger:
      - entity_id: binary_sensor.motion_sensor_158d00044cce1a
        from: "off"
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
    action:
      - data:
          entity_id: light.gateway_light_04cf8cf312cd
        service: light.turn_on
  - id: "1578413039150"
    alias: Apagar luz entrada cuando no hay movimiento
    description: ""
    trigger:
      - entity_id: binary_sensor.motion_sensor_158d00044cce1a
        from: "on"
        platform: state
        to: "off"
    condition: []
    action:
      - data:
          entity_id: light.gateway_light_04cf8cf312cd
        service: light.turn_off
  # - id: encender_luz_despacho_movimiento
  #   alias: Encender luz despacho cuando hay movimiento
  #   description: ""
  #   trigger:
  #     - entity_id: binary_sensor.motion_sensor_158d0003d1288c
  #       from: "off"
  #       platform: state
  #       to: "on"
  #   condition:
  #     - condition: state
  #       entity_id: sun.sun
  #       state: below_horizon
  #   action:
  #     - data:
  #         entity_id: light.luz_despacho
  #       service: light.turn_on
  # - id: apagar_luz_despacho_movimiento
  #   alias: Apagar luz despacho cuando no hay movimiento
  #   description: ""
  #   trigger:
  #     - entity_id: binary_sensor.motion_sensor_158d0003d1288c
  #       from: "on"
  #       platform: state
  #       to: "off"
  #   condition: []
  #   action:
  #     - data:
  #         entity_id: light.luz_despacho
  #       service: light.turn_off
