homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d0003ce68d2:
      friendly_name: Sensor puerta entrada
    binary_sensor.motion_sensor_158d00044cce1a:
      friendly_name: Sensor movimiento pasillo
    sensor.illumination_04cf8cf312cd:
      friendly_name: Sensor iluminación pasillo
    climate.netatmo_smart_thermostat:
      friendly_name: Termostato

automation:
  - id: BACKUP Notificar ERROR
    alias: Notificar error backup
    trigger:
      - platform: state
        entity_id: binary_sensor.backups_stale
        from: 'off'
        to: 'on'
    condition: []
    action:
      - data:
          title: "Backups are Stale"
          message: "Please visit the 'Home Assistant Google Drive Backup' add-on status page for details."
        service: notify.telegram
