homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d0003ce68d2:
      friendly_name: Sensor puerta entrada
    binary_sensor.motion_sensor_158d00044cce1a:
      friendly_name: Sensor movimiento pasillo
    sensor.illumination_04cf8cf312cd:
      friendly_name: Sensor iluminación pasillo
    climate.netatmo_smart_thermostat:
      friendly_name: Termostato
    binary_sensor.switch_158d000373c0dc:
      friendly_name: Interruptor mesilla
    binary_sensor.cube_158d0002a6f5e7:
      friendly_name: Cubo salón

automation:
  - id: "snapshots_went_stale"
    alias: Snapshots went stale
    trigger:
      - platform: state
        entity_id: binary_sensor.snapshots_stale
        from: "False"
        to: "True"
    condition: []
    action:
      - data:
          title: "Snapshots are Stale"
          message: "Please visit the 'Hass.io Google Drive Backup' add-on status page for details."
        service: notify.telegram
  - alias: Toggle luz Baño
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d000373c0dc
          click_type: single
    action:
      service: light.toggle
      entity_id: light.luz_espejo_bano
